spring:
  #datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://my-mysql.cdokwwuykz7h.ap-northeast-2.rds.amazonaws.com:3306/byeoljali?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
#logging.level:
#  org.hibernate.SQL: debug
# org.hibernate.type: trace