apiVersion: apps/v1

# 정의하는 리소스 Deployment, pod, service 등
# Deployment -> pod 관리
kind: Deployment
# 배포 이름, 레이블
metadata:
  name: seodangdogfe
  labels:
    app: seodangdogfe
# 배포 리소스
spec:
  replicas: 3 # 복제본 개수
  strategy:
    type: Recreate # pod 삭제 후 새로 생성하기 옵션
  selector:
    matchLabels:
      app: seodangdogfe
  template:
    metadata:
      labels:
        app: seodangdogfe
        tier: seodangdogfe
    spec:
      containers:
        - name: seodangdogfe
          image: kal72222222/seodangdogfe:latest
          imagePullPolicy: Always # 무조건 최신 이미지 가져오기
          ports:
            - containerPort: 3000 # 컨테이너 포트 (내부) 지정하기
              name: seodangdogfe
---
apiVersion: v1
# 파드 네트워크 관리
kind: Service
metadata:
  name: seodangdogfe
  labels:
    app: seodangdogfe
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: seodangdogfe
    tier: seodangdogfe
  type: LoadBalancer
